"""
Generation API Blueprint

Handles playlist generation endpoints.
"""

import traceback
from flask import Blueprint, jsonify, request
from services.system_account import (
    parse_track_ids_from_text,
    get_tracks_by_ids,
    get_public_spotify,
    create_playlist_on_system_account,
    discard_playlist,
    SystemTokenExpiredError,
    SpotifyRateLimitedError,
    MAX_PASTED_TRACKS,
    SEARCH_MAX_LIMIT,
)
from services.logic_api import (
    generate_from_text,
    recommend_from_tracks,
    LogicGenerationError,
)
from utils.rate_limit import rate_limit_required

generation_bp = Blueprint("generation", __name__)

DECLINED_HINT = (
    "Try adding more songs, or some better-known ones, so the AI has more to "
    "work from."
)


def build_playlist(populate):
    """
    Create a draft playlist and hand it to populate(playlist_id).

    A failed generation would otherwise strand a "Work in Progress" playlist
    on the system account, so the draft is discarded before the error escapes.

    Args:
        populate: Callable taking the new playlist ID, returning the Logic
                  API result dict

    Returns:
        dict: JSON-serializable response describing the finished playlist
    """
    playlist_id = create_playlist_on_system_account(
        "GEN: Work in Progress",
        "Being generated by the Logic API",
    )

    try:
        result = populate(playlist_id)
    except Exception:
        discard_playlist(playlist_id)
        raise

    return {
        "playlist_id": playlist_id,
        "playlist_url": f"https://open.spotify.com/playlist/{playlist_id}",
        "title": result["title"],
        "description": result["description"],
        "tracks": result["tracks"],
        "not_found": result.get("not_found", []),
    }


@generation_bp.route("/generate/test-rate-limit", methods=["POST"])
@rate_limit_required
def test_rate_limit():
    """
    Test endpoint to verify rate limiting without calling the Logic API.

    Returns:
        JSON: Mock playlist generation response
    """
    import time
    # Simulate a small delay like a real API call
    time.sleep(0.5)

    return jsonify({
        "playlist_id": "test_playlist_123",
        "playlist_url": "https://open.spotify.com/playlist/test_playlist_123",
        "title": "Test Rate Limit Playlist",
        "description": "This is a test response to verify rate limiting works correctly.",
        "tracks": [
            {
                "name": "Test Song 1",
                "artist": "Test Artist 1",
                "album": "Test Album",
                "spotify_url": "https://open.spotify.com/track/test1"
            },
            {
                "name": "Test Song 2",
                "artist": "Test Artist 2",
                "album": "Test Album",
                "spotify_url": "https://open.spotify.com/track/test2"
            }
        ],
        "not_found": []
    })


@generation_bp.route("/tracks/resolve", methods=["POST"])
def resolve_tracks():
    """
    Resolve pasted Spotify track links into track details.

    Request body:
        text: Pasted text containing track URLs, URIs, or IDs

    Returns:
        JSON: { tracks: [...], not_found: [...], truncated: bool }
    """
    data = request.get_json() or {}
    text = data.get("text", "")

    track_ids = parse_track_ids_from_text(text)
    if not track_ids:
        return jsonify({
            "error": "no_tracks_found",
            "message": "No Spotify song links found. Copy songs from Spotify "
                       "and paste them here."
        }), 400

    truncated = len(track_ids) > MAX_PASTED_TRACKS
    tracks, not_found = get_tracks_by_ids(track_ids[:MAX_PASTED_TRACKS])

    return jsonify({
        "tracks": tracks,
        "not_found": not_found,
        "truncated": truncated,
    })


@generation_bp.route("/generate/from-tracks", methods=["POST"])
@rate_limit_required
def generate_from_tracks():
    """
    Generate a new playlist from a list of seed track IDs.

    Request body:
        track_ids: List of Spotify track IDs

    Returns:
        JSON: Generated playlist info with tracks
    """
    data = request.get_json() or {}
    track_ids = data.get("track_ids") or []

    if not isinstance(track_ids, list) or not track_ids:
        return jsonify({
            "error": "missing_tracks",
            "message": "Add at least one song to generate from"
        }), 400

    try:
        seed_tracks, _ = get_tracks_by_ids(track_ids[:MAX_PASTED_TRACKS])
        if not seed_tracks:
            return jsonify({
                "error": "tracks_not_found",
                "message": "None of those songs could be found on Spotify"
            }), 400

        seed_data = [
            {k: t[k] for k in ("name", "artist", "album", "release_date")}
            for t in seed_tracks
        ]

        return jsonify(build_playlist(
            lambda playlist_id: recommend_from_tracks(seed_data, playlist_id)
        ))

    except (SystemTokenExpiredError, SpotifyRateLimitedError):
        raise

    except LogicGenerationError as e:
        return jsonify({
            "error": "generation_declined",
            "message": f"{e} {DECLINED_HINT}"
        }), 422

    except ValueError as e:
        return jsonify({
            "error": "generation_error",
            "message": str(e)
        }), 400

    except Exception:
        traceback.print_exc()
        return jsonify({
            "error": "generation_error",
            "message": "Failed to generate playlist. Please try again."
        }), 500


@generation_bp.route("/generate/from-text", methods=["POST"])
@rate_limit_required
def generate_from_text_route():
    """
    Generate a new playlist based on a text description.

    Request body:
        description: Text description of desired playlist

    Returns:
        JSON: Generated playlist info with tracks
    """
    data = request.get_json()
    description = data.get("description", "").strip()

    if not description:
        return jsonify({
            "error": "missing_description",
            "message": "description is required"
        }), 400

    try:
        return jsonify(build_playlist(
            lambda new_id: generate_from_text(description, new_id)
        ))

    except (SystemTokenExpiredError, SpotifyRateLimitedError):
        raise

    except LogicGenerationError as e:
        return jsonify({
            "error": "generation_declined",
            "message": f"{e} {DECLINED_HINT}"
        }), 422

    except ValueError as e:
        return jsonify({
            "error": "generation_error",
            "message": str(e)
        }), 400

    except Exception:
        traceback.print_exc()
        return jsonify({
            "error": "generation_error",
            "message": "Failed to generate playlist. Please try again."
        }), 500


@generation_bp.route("/search/tracks", methods=["GET"])
def search_tracks():
    """
    Search Spotify for tracks to seed a playlist.

    Query Parameters:
        q: Search query
        limit: Max results (capped at SEARCH_MAX_LIMIT)

    Returns:
        JSON: { tracks: [...], query: str, count: int }
    """
    query = request.args.get("q", "").strip()

    if len(query) < 2:
        return jsonify({
            "error": "invalid_query",
            "message": "Query must be at least 2 characters"
        }), 400

    try:
        limit = min(int(request.args.get("limit", SEARCH_MAX_LIMIT)), SEARCH_MAX_LIMIT)
    except ValueError:
        limit = SEARCH_MAX_LIMIT

    try:
        results = get_public_spotify().search(q=query, type="track", limit=limit)

        tracks = []
        # Spotify returns null entries for items the app can't access.
        for item in filter(None, results["tracks"]["items"]):
            album = item.get("album") or {}
            tracks.append({
                "id": item["id"],
                "name": item["name"],
                "artist": item["artists"][0]["name"] if item.get("artists") else "Unknown",
                "album": album.get("name", "Unknown"),
                "release_date": album.get("release_date", ""),
                "image": album["images"][0]["url"] if album.get("images") else None,
            })

        return jsonify({"tracks": tracks, "query": query, "count": len(tracks)})

    except Exception:
        traceback.print_exc()
        return jsonify({
            "error": "search_error",
            "message": "Failed to search tracks"
        }), 500
